### ISSUE TITLE
clicked login going to https://138.197.221.3/login

### ISSUE THREAD

**Issue by todokku** [taloncjones/Mini_TTV#1]
hi talon , 
clicked login going to https://138.197.221.3/login
& if any api variable must be set tell to me , in the realme.md of repo not exist any tutorial to run it again.
finest regards

**Comment by taloncjones** [comment]
Hi todokku,
Thanks for the interest! I'm still in the process of updating the README. The 138.197.221.3 IP address was the test server I was using at the time, and should be set to your own version in the src/components/Url.json file. I'll be sure to update the IP and ports in the README.

**Comment by taloncjones** [comment]
Hi todokku,
I've updated the readme with setup/running instructions. Hopefully that helps!
